In [25]:
import pandas as pd
import sys

In [26]:
if len(sys.argv) != 2:
    print("Usage: python3 load.py <file_path>")
    sys.exit(1)
file_path = sys.argv[1]

Usage: python3 load.py <file_path>

SystemExit: ignored

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [2]:
df = pd.read_csv("Housing.csv")

In [3]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [7]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [12]:
missing_values_summary = df.isnull().sum()

print("Missing Values Summary:")
print(missing_values_summary)

Missing Values Summary:
price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

## **Property with the highest number of rooms and parking and the highest price:**

In [14]:
# Sort the DataFrame by 'bedrooms', 'parking', and 'price' columns in descending order
sorted_data = df.sort_values(by=['bedrooms', 'parking', 'price'], ascending=[False, False, False])

property_with_highest_rooms_and_parking = sorted_data.iloc[0]


print("Property with the highest number of rooms and parking and the highest price:")
print(property_with_highest_rooms_and_parking)

Property with the highest number of rooms and parking and the highest price:
price                   3500000
area                       3600
bedrooms                      6
bathrooms                     1
stories                       2
mainroad                    yes
guestroom                    no
basement                     no
hotwaterheating              no
airconditioning              no
parking                       1
prefarea                     no
furnishingstatus    unfurnished
Name: 395, dtype: object

## **Price analysis for furnishingstatu**

In [18]:
# Calculate the average price for each furnishing status category

average_price_furnished = df[df['furnishingstatus'] == 'furnished']['price'].mean()
average_price_semi_furnished = df[df['furnishingstatus'] == 'semi-furnished']['price'].mean()
average_price_unfurnished = df[df['furnishingstatus'] == 'unfurnished']['price'].mean()


print("Average Price for Furnished Properties:", average_price_furnished)
print("Average Price for Semi-Furnished Properties:", average_price_semi_furnished)
print("Average Price for Unfurnished Properties:", average_price_unfurnished)

average_prices = {
    'Furnished': average_price_furnished,
    'Semi-Furnished': average_price_semi_furnished,
    'Unfurnished': average_price_unfurnished
}

max_category_name, max_average_price = max(average_prices.items(), key=lambda x: x[1])



print("\nCategory with Maximum Average Price:", max_category_name)
print("Maximum Average Price:", max_average_price)

Average Price for Furnished Properties: 5495696.0
Average Price for Semi-Furnished Properties: 4907524.22907489
Average Price for Unfurnished Properties: 4013831.4606741574

Category with Maximum Average Price: Furnished
Maximum Average Price: 5495696.0

## Property with the Biggest Area on Main Road and Average Price of Main Road Properties

In [22]:
# Filter the DataFrame to select properties located on a main road
main_road_properties = df[df['mainroad'] == 'yes']

# Find the property with the biggest area among main road properties
biggest_area_property = main_road_properties[main_road_properties['area'] == main_road_properties['area'].max()]

# Calculate the average price of main road properties
average_price_main_road = main_road_properties['price'].mean()


print("Property with the Biggest Area on Main Road:")
print(biggest_area_property)

print("Average Price of Main Road Properties:", average_price_main_road)

#Max house prices
print("Max house prices", df["price"].max())

Property with the Biggest Area on Main Road:
      price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
7  10150000  16200         5          3        2      yes        no       no

  hotwaterheating airconditioning  parking prefarea furnishingstatus
7              no              no        0       no      unfurnished
Average Price of Main Road Properties: 4991777.329059829
Max house prices 13300000

In [23]:
# Group the data by 'prefarea' and 'furnishingstatus'
average_price_by_area_and_furnishing = df.groupby(['prefarea', 'furnishingstatus'])['price'].mean()

#  the average prices by preferred area and furnishing
print("Average Prices by Preferred Area and Furnishing Status:")
print(average_price_by_area_and_furnishing)

Average Prices by Preferred Area and Furnishing Status:
prefarea  furnishingstatus
no        furnished           5.121072e+06
          semi-furnished      4.614918e+06
          unfurnished         3.731000e+06
yes       furnished           6.340779e+06
          semi-furnished      5.892257e+06
          unfurnished         5.256576e+06
Name: price, dtype: float64

In [28]:
#file_path = "eda-in-1.txt"

# Open the file in write mode and write the insights to it
with open(file_path + '/eda-in-1.txt', "w") as file:
    file.write("Insights and Results:\n\n")

    # Insight 1
    file.write("Insight 1: Property with the highest number of rooms and parking and the highest price:\n")
    file.write(property_with_highest_rooms_and_parking.to_string() + "\n\n")

    # Insight 2
    file.write("Insight 2: Price analysis for furnishing status\n")
    file.write("Average Price for Furnished Properties:\n")
    file.write(str(average_price_furnished) + "\n\n")
    file.write("Average Price for Semi-Furnished Properties:\n")
    file.write(str(average_price_semi_furnished) + "\n\n")
    file.write("Average Price for Unfurnished Properties:\n")
    file.write(str(average_price_unfurnished) + "\n\n")

    # Insight 3 (Property on Main Road)
    file.write("Insight 3: Property with the Biggest Area on Main Road:\n")
    file.write(biggest_area_property.to_string() + "\n\n")
    file.write("Average Price of Main Road Properties:\n")
    file.write(str(average_price_main_road) + "\n\n")

    # Insight 4 (Max House Prices)
    file.write("Insight 4: Max House Prices:\n")
    file.write("Max House Prices: " + str(df["price"].max()) + "\n\n")

    # Insight 5 (Average Prices by Preferred Area and Furnishing Status)
    file.write("Insight 5: Average Prices by Preferred Area and Furnishing Status:\n")
    file.write(average_price_by_area_and_furnishing.to_string() + "\n\n")

    # Insight 6 (Add more insights if needed)

print("Insights have been saved to 'eda-in-1.txt'.")

Insights have been saved to 'eda-in-1.txt'.